import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import { LenisProvider } from "@/providers/LenisProvider";
import { PushMenuProvider } from "@/components/PushMenu";
import { helveticaNeue, helveticaNeueCn } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();

  const [navigation, settings] = await Promise.all([
    client.getSingle("navigation").catch(() => null),
    client.getSingle("settings").catch(() => null),
  ]);

  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${helveticaNeue.variable} ${helveticaNeueCn.variable} antialiased`}>
          <LenisProvider>
            <PushMenuProvider navigation={navigation} settings={settings}>
              {children}
            </PushMenuProvider>
          </LenisProvider>
          <PrismicPreview repositoryName={repositoryName} />
        </body>
      </html>
    </ViewTransitions>
  );
}
