import type { Metadata } from "next";
import { ViewTransitions } from "next-view-transitions";
import { PrismicPreview } from "@prismicio/next";
import { createClient, repositoryName } from "@/prismicio";
import { LenisProvider, LogosProvider } from "@/providers";
import { PushMenuProvider } from "@/components/PushMenu";
import { helveticaNeue, helveticaNeueCn, instrumentSans, instrumentSerif } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();

  const [navigation, settings, logos, reviews] = await Promise.all([
    client.getSingle("navigation").catch(() => null),
    client.getSingle("settings").catch(() => null),
    client.getSingle("logos").catch(() => null),
    client.getAllByType("review").catch(() => []),
  ]);

  return (
    <ViewTransitions>
      <html lang="en">
        <body className={`${helveticaNeue.variable} ${helveticaNeueCn.variable} ${instrumentSans.variable} ${instrumentSerif.variable} text-base md:text-lg antialiased`}>
          <LenisProvider>
            <LogosProvider logos={logos}>
              <PushMenuProvider navigation={navigation} settings={settings} reviews={reviews}>
                {children}
              </PushMenuProvider>
            </LogosProvider>
          </LenisProvider>
          <PrismicPreview repositoryName={repositoryName} />
        </body>
      </html>
    </ViewTransitions>
  );
}
