// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  glass_hero: dynamic(() => import("./GlassHero")),
  portfolio_list: dynamic(() => import("./PortfolioList")),
  redact_text: dynamic(() => import("./RedactText")),
  simple_hero: dynamic(() => import("./SimpleHero")),
};
